# Generated by Django 2.2 on 2021-10-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='content',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
